### ISSUE TITLE
XDarkTerror and Xmonk need updating

### ISSUE THREAD

**Issue by zonkmachine** [brummer10/XPlugs.lv2#1]
Hi! I failed to build the XPlugs.lv2

```
fatal: remote error: upload-pack: not our ref d1a69f0f02312b56c28f93f07d8b662ae1160176
Fetched in submodule path 'XDarkTerror.lv2', but it did not contain d1a69f0f02312b56c28f93f07d8b662ae1160176.
  Direct fetching of that commit failed.
```
https://github.com/brummer10/XDarkTerror.lv2/tree/d1a69f0f02312b56c28f93f07d8b662ae1160176
https://github.com/brummer10/Xmonk.lv2/tree/3f69d908245d81e8c8ffb6a1a3e16bf634e7a249

**Comment by brummer10** [comment]
Ups.
I've forgotten to push the latest changes for XDarkTerror and Xmonk to the repositories, done now. Should be fixed now.

**Comment by zonkmachine** [comment]
:+1:
