### ISSUE TITLE
Include additional libxputty plugin projects?

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/XPlugs.lv2#5]
I noticed that some of your libxputty-based plugin projects are not part of this collection:

* https://github.com/brummer10/bluesbreaker.lv2
* https://github.com/brummer10/MelMatchEQ.lv2
* https://github.com/brummer10/MetalTone
* https://github.com/brummer10/slowmo.lv2
* https://github.com/brummer10/VintageAC30.lv2
* https://github.com/brummer10/VintageTubeOverdrive.lv2

Most of these (except MelMatchEQ.lv2 and MetalTone) do not have a tagged release version yet, but many of the plugins already in this collections don't have one either.

Is there a special reason why the above projects are not included? Are you planning to include them at some point?

**Comment by brummer10** [comment]
There was a reason, but I've forgotten what it was :(
Currently I've no plans to expand the XPlugs collection. 
I like to do some work on the guitarix.vst port, porting it to DPF. That will be a huge work first as I need to write all the needed widgets. Fortunately I could take a lot from libxputty to archive that. 
So, to say, my future plan is to create a DPF cairo widget library. 
It may be possible that the XPlugs collection then become obsolete, as I may port those plugs to DPF in that run. 
The ToneTwistPlugs collection was a first step.

**Comment by SpotlightKid** [comment]
I see. Thank you for the explanation.

> It may be possible that the XPlugs collection then become obsolete

Do you still want PRs with fixes for this repo and sub-projects?

Because at this moment this repo does not compile due to errors in several sub-projects:

* Fluida.lv2 - see https://github.com/brummer10/Fluida.lv2/pull/26
* XKeyboard.lv2 - error related to midi keyboard API
* Xmonk.lv2-  item
* XPolymonk.lv2 - item

**Comment by brummer10** [comment]
> Do you still want PRs with fixes for this repo and sub-projects?

Yes, that is very welcome. I'll maintain those projects and merge pull requests happily.

**Comment by SpotlightKid** [comment]
Ok, that's good to hear.
